<?php
/**
 * Utility functions that process escape sequences.
 *
 * @package    ExternBib
 * @author     Olaf Lenz
 * @author     Jean-Noël Grad
 * @copyright  2011-2014,2022 The Authors
 * @license    https://opensource.org/licenses/BSD-3-Clause New BSD License
 * @link       https://github.com/olenz/externbib
 */

/** Conversion modes. */
class ConversionModes {
    const Newlines         = 0b00000001; ///< Replace double backslashes by a newline (strongly recommended)
    const Diacritics       = 0b00000010; ///< Remove diacritic escape sequences (see @ref diacritics2utf8)
}

/** Mapping of LaTeX diacritics escape sequences to UTF-8 symbols. */
$bibtex2utf8_array = array(
  '\\"a' => 'ä',
  '\\"A' => 'Ä',
  '\\"e' => 'ë',
  '\\"E' => 'Ë',
  '\\"i' => 'ï',
  '\\"I' => 'Ï',
  '\\"o' => 'ö',
  '\\"O' => 'Ö',
  '\\"r' => 'r̈',
  '\\"R' => 'R̈',
  '\\"u' => 'ü',
  '\\"U' => 'Ü',
  '\\"y' => 'ÿ',
  '\\"Y' => 'Ÿ',
  '\\\'a' => 'á',
  '\\\'A' => 'Á',
  '\\\'c' => 'ć',
  '\\\'C' => 'Ć',
  '\\\'e' => 'é',
  '\\\'E' => 'É',
  '\\\'i' => 'í',
  '\\\'I' => 'Í',
  '\\\'l' => 'ĺ',
  '\\\'L' => 'Ĺ',
  '\\\'n' => 'ń',
  '\\\'N' => 'Ń',
  '\\\'o' => 'ó',
  '\\\'O' => 'Ó',
  '\\\'r' => 'ŕ',
  '\\\'R' => 'Ŕ',
  '\\\'s' => 'ś',
  '\\\'S' => 'Ś',
  '\\\'u' => 'ú',
  '\\\'U' => 'Ú',
  '\\\'y' => 'ý',
  '\\\'Y' => 'Ý',
  '\\\'z' => 'ź',
  '\\\'Z' => 'Ź',
  '\\\'\\ae' => 'ǽ',
  '\\\'\\AE' => 'Ǽ',
  '\\\'\\o' => 'ǿ',
  '\\\'\\O' => 'Ǿ',
  '\\^a' => 'â',
  '\\^A' => 'Â',
  '\\^c' => 'ĉ',
  '\\^C' => 'Ĉ',
  '\\^e' => 'ê',
  '\\^E' => 'Ê',
  '\\^g' => 'ĝ',
  '\\^G' => 'Ĝ',
  '\\^h' => 'ĥ',
  '\\^H' => 'Ĥ',
  '\\^i' => 'î',
  '\\^I' => 'Î',
  '\\^j' => 'ĵ',
  '\\^J' => 'Ĵ',
  '\\^o' => 'ô',
  '\\^O' => 'Ô',
  '\\^r' => 'r̂',
  '\\^R' => 'R̂',
  '\\^s' => 'ŝ',
  '\\^S' => 'Ŝ',
  '\\^u' => 'û',
  '\\^U' => 'Û',
  '\\^w' => 'ŵ',
  '\\^W' => 'Ŵ',
  '\\^x' => 'x̂',
  '\\^X' => 'X̂',
  '\\^y' => 'ŷ',
  '\\^Y' => 'Ŷ',
  '\\`a' => 'à',
  '\\`A' => 'À',
  '\\`e' => 'è',
  '\\`E' => 'È',
  '\\`i' => 'ì',
  '\\`I' => 'Ì',
  '\\`o' => 'ò',
  '\\`O' => 'Ò',
  '\\`u' => 'ù',
  '\\`U' => 'Ù',
  '\\`y' => 'ỳ',
  '\\`Y' => 'Ỳ',
  '\\~a' => 'ã',
  '\\~A' => 'Ã',
  '\\~e' => 'ẽ',
  '\\~E' => 'Ẽ',
  '\\~i' => 'ĩ',
  '\\~I' => 'Ĩ',
  '\\~n' => 'ñ',
  '\\~N' => 'Ñ',
  '\\~o' => 'õ',
  '\\~O' => 'Õ',
  '\\~u' => 'ũ',
  '\\~U' => 'Ũ',
  '\\~v' => 'ṽ',
  '\\~V' => 'Ṽ',
  '\\~y' => 'ỹ',
  '\\~Y' => 'Ỹ',
  '\\=a' => 'ā',
  '\\=A' => 'Ā',
  '\\=e' => 'ē',
  '\\=E' => 'Ē',
  '\\=I' => 'Ī',
  '\\=i' => 'ī',
  '\\=o' => 'ō',
  '\\=O' => 'Ō',
  '\\=u' => 'ū',
  '\\=U' => 'Ū',
  '\\=v' => 'v̄',
  '\\=V' => 'V̄',
  '\\=x' => 'x̄',
  '\\=X' => 'X̄',
  '\\=y' => 'ȳ',
  '\\=Y' => 'Ȳ',
  '\\=\\ae' => 'ǣ',
  '\\=\\AE' => 'Ǣ',
  '\\.a' => 'ȧ',
  '\\.A' => 'Ȧ',
  '\\.b' => 'ḃ',
  '\\.B' => 'Ḃ',
  '\\.c' => 'ċ',
  '\\.C' => 'Ċ',
  '\\.d' => 'ḋ',
  '\\.D' => 'Ḋ',
  '\\.e' => 'ė',
  '\\.E' => 'Ė',
  '\\.f' => 'ḟ',
  '\\.F' => 'Ḟ',
  '\\.g' => 'ġ',
  '\\.G' => 'Ġ',
  '\\.h' => 'ḣ',
  '\\.H' => 'Ḣ',
  '\\.I' => 'İ',
  '\\.k' => 'k̇',
  '\\.K' => 'K̇',
  '\\.l' => 'l̇',
  '\\.L' => 'L̇',
  '\\.m' => 'ṁ',
  '\\.M' => 'Ṁ',
  '\\.n' => 'ṅ',
  '\\.N' => 'Ṅ',
  '\\.o' => 'ȯ',
  '\\.O' => 'Ȯ',
  '\\.p' => 'ṗ',
  '\\.P' => 'Ṗ',
  '\\.q' => 'q̇',
  '\\.Q' => 'Q̇',
  '\\.r' => 'ṙ',
  '\\.R' => 'Ṙ',
  '\\.s' => 'ṡ',
  '\\.S' => 'Ṡ',
  '\\.t' => 'ṫ',
  '\\.T' => 'Ṫ',
  '\\.u' => 'u̇',
  '\\.U' => 'U̇',
  '\\.v' => 'v̇',
  '\\.V' => 'V̇',
  '\\.w' => 'ẇ',
  '\\.W' => 'Ẇ',
  '\\.x' => 'ẋ',
  '\\.X' => 'Ẋ',
  '\\.y' => 'ẏ',
  '\\.Y' => 'Ẏ',
  '\\.z' => 'ż',
  '\\.Z' => 'Ż',
  '\\c c' => 'ç',
  '\\c C' => 'Ç',
  '\\c d' => 'ḑ',
  '\\c D' => 'Ḑ',
  '\\c e' => 'ȩ',
  '\\c E' => 'Ȩ',
  '\\c h' => 'ḩ',
  '\\c H' => 'Ḩ',
  '\\c g' => 'ģ',
  '\\c G' => 'Ģ',
  '\\c k' => 'ķ',
  '\\c K' => 'Ķ',
  '\\c l' => 'ļ',
  '\\c L' => 'Ļ',
  '\\c n' => 'ņ',
  '\\c N' => 'Ņ',
  '\\c r' => 'ŗ',
  '\\c R' => 'Ŗ',
  '\\c s' => 'ş',
  '\\c S' => 'Ş',
  '\\c t' => 'ţ',
  '\\c T' => 'Ţ',
  '\\d a' => 'ạ',
  '\\d A' => 'Ạ',
  '\\d b' => 'ḅ',
  '\\d B' => 'Ḅ',
  '\\d c' => 'c̣',
  '\\d C' => 'C̣',
  '\\d d' => 'ḍ',
  '\\d D' => 'Ḍ',
  '\\d e' => 'ẹ',
  '\\d E' => 'Ẹ',
  '\\d f' => 'f̣',
  '\\d F' => 'F̣',
  '\\d g' => 'g̣',
  '\\d G' => 'G̣',
  '\\d h' => 'ḥ',
  '\\d H' => 'Ḥ',
  '\\d i' => 'ị',
  '\\d I' => 'Ị',
  '\\d j' => 'j̣',
  '\\d J' => 'J̣',
  '\\d k' => 'ḳ',
  '\\d K' => 'Ḳ',
  '\\d l' => 'ḷ',
  '\\d L' => 'Ḷ',
  '\\d m' => 'ṃ',
  '\\d M' => 'Ṃ',
  '\\d n' => 'ṇ',
  '\\d N' => 'Ṇ',
  '\\d o' => 'ọ',
  '\\d O' => 'Ọ',
  '\\d p' => 'p̣',
  '\\d P' => 'P̣',
  '\\d q' => 'q̣',
  '\\d Q' => 'Q̣',
  '\\d r' => 'ṛ',
  '\\d R' => 'Ṛ',
  '\\d s' => 'ṣ',
  '\\d S' => 'Ṣ',
  '\\d t' => 'ṭ',
  '\\d T' => 'Ṭ',
  '\\d u' => 'ụ',
  '\\d U' => 'Ụ',
  '\\d v' => 'ṿ',
  '\\d V' => 'Ṿ',
  '\\d w' => 'ẉ',
  '\\d W' => 'Ẉ',
  '\\d x' => 'x̣',
  '\\d X' => 'X̣',
  '\\d y' => 'ỵ',
  '\\d Y' => 'Ỵ',
  '\\d z' => 'ẓ',
  '\\d Z' => 'Ẓ',
  '\\k a' => 'ą',
  '\\k A' => 'Ą',
  '\\k e' => 'ę',
  '\\k E' => 'Ę',
  '\\k i' => 'į',
  '\\k I' => 'Į',
  '\\k n' => 'n̨',
  '\\k N' => 'N̨',
  '\\k o' => 'ǫ',
  '\\k O' => 'Ǫ',
  '\\k u' => 'ų',
  '\\k U' => 'Ų',
  '\\k s' => 's̨',
  '\\k S' => 'S̨',
  '\\k z' => 'z̨',
  '\\k Z' => 'Z̨',
  '\\r a' => 'å',
  '\\r A' => 'Å',
  '\\r u' => 'ů',
  '\\r U' => 'Ů',
  '\\r w' => 'ẘ',
  '\\r y' => 'ẙ',
  '\\u a' => 'ă',
  '\\u A' => 'Ă',
  '\\u e' => 'ĕ',
  '\\u E' => 'Ĕ',
  '\\u g' => 'ğ',
  '\\u G' => 'Ğ',
  '\\u i' => 'ĭ',
  '\\u I' => 'Ĭ',
  '\\u o' => 'ŏ',
  '\\u O' => 'Ŏ',
  '\\u s' => 's̆',
  '\\u S' => 'S̆',
  '\\u u' => 'ŭ',
  '\\u U' => 'Ŭ',
  '\\u y' => 'y̆',
  '\\u Y' => 'Y̆',
  '\\v a' => 'ǎ',
  '\\v A' => 'Ǎ',
  '\\v c' => 'č',
  '\\v C' => 'Č',
  '\\v d' => 'ď',
  '\\v D' => 'Ď',
  '\\v e' => 'ě',
  '\\v E' => 'Ě',
  '\\v g' => 'ǧ',
  '\\v G' => 'Ǧ',
  '\\v h' => 'ȟ',
  '\\v H' => 'Ȟ',
  '\\v i' => 'ǐ',
  '\\v I' => 'Ǐ',
  '\\v j' => 'ǰ',
  '\\v k' => 'ǩ',
  '\\v K' => 'Ǩ',
  '\\v l' => 'ľ',
  '\\v L' => 'Ľ',
  '\\v n' => 'ň',
  '\\v N' => 'Ň',
  '\\v o' => 'ǒ',
  '\\v O' => 'Ǒ',
  '\\v r' => 'ř',
  '\\v R' => 'Ř',
  '\\v s' => 'š',
  '\\v S' => 'Š',
  '\\v t' => 'ť',
  '\\v T' => 'Ť',
  '\\v u' => 'ǔ',
  '\\v U' => 'Ǔ',
  '\\v z' => 'ž',
  '\\v Z' => 'Ž',
  '\\H a' => 'a̋',
  '\\H A' => 'A̋',
  '\\H e' => 'e̋',
  '\\H E' => 'E̋',
  '\\H i' => 'i̋',
  '\\H I' => 'I̋',
  '\\H m' => 'm̋',
  '\\H M' => 'M̋',
  '\\H o' => 'ő',
  '\\H O' => 'Ő',
  '\\H u' => 'ű',
  '\\H U' => 'Ű',
  '\\H y' => 'ӳ',
  '\\H Y' => 'Y̋',
  '{\\aa}' => 'å',
  '{\\AA}' => 'Å',
  '{\\ae}' => 'æ',
  '{\\AE}' => 'Æ',
  '{\\oe}' => 'œ',
  '{\\OE}' => 'Œ',
  '{\\dh}' => 'ð',
  '{\\DH}' => 'Ð',
  '{\\dj}' => 'đ',
  '{\\DJ}' => 'Đ',
  '{\\ij}' => '&ijlig;',
  '{\\IJ}' => '&IJlig;',
  '{\\ss}' => 'ß',
  '{\\SS}' => 'ẞ',
  '{\\th}' => 'Þ',
  '{\\TH}' => 'þ',
  '{\\ng}' => 'ŋ',
  '{\\NG}' => 'Ŋ',
  '{\\i}' => 'ı',
  '{\\l}' => 'ł',
  '{\\L}' => 'Ł',
  '{\\o}' => 'ø',
  '{\\O}' => 'Ø',
  '{\\S}' => '§',
  '{\\P}' => '¶',
  '---' => '&mdash;',
  '--' => '&ndash;',
  '\\&' => '&amp;',
  '\\-' => '',
  '\\,' => ' ',
  '\\%' => '%',
  '\\$' => '&#36;',
  '\\_' => '_',
  '\\#' => '#',
  '~' => ' ',
);

$bibtexenc = array_keys($bibtex2utf8_array);
$utf8enc = array_values($bibtex2utf8_array);

/**
 * Replace diacritic escape sequences with their corresponding UTF-8 symbols.
 *
 * @param  string  $string  The BibTeX string.
 * @return string  The UTF-8 version.
 */
function diacritics2utf8($string) {
  global $bibtexenc;
  global $utf8enc;
  $graph_pat = '[ilLoOSP]|aa|AA|ae|AE|oe|OE|dh|DH|dj|DJ|ij|IJ|ng|NG|ss|SS|th|TH';
  // replace TeX escape sequences by UTF-8 characters
  $string = preg_replace('/\\\\('.$graph_pat.')(?: |(?=[^a-zA-Z]|$))/', '{\\\\$1}', $string);
  $string = preg_replace('/\\{\\{\\\\('.$graph_pat.')\\}\\}/', '{\\\\$1}', $string);
  $string = preg_replace('/(\\\\[\"\'\\^\\.`~=])\\{(\\\\?[a-zA-Z]+)\\}/', '$1$2', $string);
  $string = preg_replace('/(\\\\[bcdkruvH])\\{(\\\\?[a-zA-Z]+)\\}/', '$1 $2', $string);
  $string = str_replace($bibtexenc, $utf8enc, $string);
  // replace quotation marks
  if (strpos($string, '`') !== false) {
    $string = preg_replace('/(?<=^|[\\s\\[\\{\\(;]|--)``/', '&ldquo;', $string);
    $string = preg_replace('/(?<=^|[\\s\\[\\{\\(;]|--)`/',  '&lsquo;', $string);
    $string = preg_replace('/\'\'\'(?=[\\s\\.:;,\\!\\?\\]\\}\\)]|--|$)/', '&rsquo;&rdquo;', $string);
    $string = preg_replace('/\'\'(?=[\\s\\.:;,\\!\\?\\]\\}\\)]|--|$)/', '&rdquo;', $string);
    $string = preg_replace('/\'(?=[\\s\\.:;,\\!\\?\\]\\}\\)]|--|$)/', '&rsquo;', $string);
  }
  return $string;
}

/**
 * Substitute LaTeX escape sequences and macros by equivalent HTML.
 *
 * @param  string  $value  The LaTeX string.
 * @param  int     $modes  LaTeX-to-HTML conversions to apply.
 * @return string  The converted string.
 */
function convert_latex_string($value, $modes) {
  if ($modes and (($modes & ConversionModes::Newlines) == 0)) {
    throw "Cannot process LaTeX without first substituting newlines";
  }
  if ($modes == 0) {
    return $value;
  }
  if ($modes & ConversionModes::Newlines) {
    $value = str_replace("\\\\", "\n", $value);
  }
  if ($modes & ConversionModes::Diacritics) {
    $value = diacritics2utf8($value);
  }
  return $value;
}

?>
